# Generated by Django 5.2.3 on 2025-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_grade_school_student_grade_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
